[workspace]
members = [
  "todo-cli",
  "todo-core",
]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2021"
authors = ["Donald Huber-Youmans"]

[workspace.dependencies]
clap = { version = "4.5.47", features = ["derive"] }
clap_complete = "4.5.0"
env_logger = "0.11.8"
