[package]
name = "todo"
version = "0.1.1"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4.5.47", features = ["derive"] }
dirs = "6.0.0"
dotenv = "0.15.0"
glob = "0.3.3"
microxdg = "0.2.0"
rusqlite = "0.37.0"
serde = { version = "1.0.225", features = ["derive"] }
tabled = "0.15"
toml = "0.9.7"
